config/routes.rb
Rails.application.routes.draw do
  get 'search' => "searches#search"
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about"
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
  resources :books, only: [:index,:show,:create,:destroy,:edit,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: {minimum: 2,maximum: 20},uniqueness: true
  validates :introduction, length: {maximum: 50}

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # フォロー機能
  has_many :relationships, foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :following

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end
  # /フォロー機能
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def ensure_current_user
    if current_user.id != params[:id].to_i
     redirect_to user_path(current_user.id)
    end
  end

  def require_login
    unless current_user
        redirect_to new_user_session_path, notice: 'Please sign in to get started!'
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:name])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_login
  before_action :ensure_current_user_book, {only: [:edit]}

  def index
    @book=Book.new
    @user=current_user
    @books=Book.all
  end

  def show
    @book_user=Book.find(params[:id])
    @book=Book.new
    @book_comment=BookComment.new
  end

  def create
    @book=Book.new(book_params)
    @book.user_id= current_user.id
    if @book.save
      flash[:success]="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user=current_user
      @books=Book.all
      render "books/index"
    end
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:success]="You have updated book successfully."
    else
      render "books/edit"
    end
  end

    private

  def book_params
    params.require(:book).permit(:title,:body,:user_id)
  end
end

  def ensure_current_user_book
    book = Book.find(params[:id])
    if current_user.id != book.user.id
     redirect_to books_path
    end
  end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  def create
    following = current_user.relationships.build(follower_id: params[:user_id])
    following.save
    redirect_to request.referrer || root_path
  end

  def destroy
    following = current_user.relationships.find_by(follower_id: params[:user_id])
    following.destroy
    redirect_to request.referrer || root_path
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      elsif method == 'forward'
        User.where('name LIKE ?', "#{content}%")
      elsif method == 'rear'
        User.where('name LIKE ?', "%#{content}")
      elsif method == 'partial'
        User.where('name LIKE ?', "%#{content}%")
      end
    elsif model == 'book'
      if method == 'perfect'
        Book.where(body: content)
      elsif method == 'forward'
        Book.where('body LIKE ?', "#{content}%")
      elsif method == 'rear'
        Book.where('body LIKE ?', "%#{content}")
      elsif method == 'partial'
        Book.where('body LIKE ?', "%#{content}%")
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  before_action :ensure_current_user, {only: [:edit]}

  def index
    @user=current_user
    @book=Book.new
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
    @books=Book.where(user_id: @user.id)
    @book=Book.new
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=current_user
    if @user.update(user_params)
     redirect_to user_path(current_user.id)
     flash[:success]="You have updated user successfully."
    else
      render "users/edit"
    end
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

    private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_like.erb
<%= link_to book_favorites_path(book), method: :post, remote: true do %>
  <i class="fas fa-heart"><%= book.favorites.count %></i>
<% end %>

app/views/books/_show.html.erb
          <% book_user.book_comments.each do |book_comment| %>
            <table class="table-comments">
              <thead>
                <tr>
                  <th>
                    <%= link_to user_path(book_comment.user) do %>
                     <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %><br>
                     <%= book_comment.user.name %>
                    <% end %>
                  </th>
                  <th>
                    <%= book_comment.comment %>
                  </th>
                  <th>
                    <% if book_comment.user == current_user %>
                      <div class="comment-delete">
                        <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "本当に削除しますか？"} %>
                      </div>
                    <% end %>
                  </th>
                </tr>
              </thead>
            </table>
          <% end %>

app/views/books/_unlike.erb
<%= link_to book_favorites_path(book), method: :delete, remote: true do %>
  <i class="fas fa-heart" style="color:red;"><%= book.favorites.count %></i>
<% end %>

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class ="col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <div class="container px-5 px-sm-0">
          <div class="row">
            <div id="error_explanation" class="alert alert-danger">
              <h3 class="alert_message">
               <%= @book.errors.count %> error prohibited this obj from being saved:
              </h3>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
        <%= form_with model:@book, local:true do |f| %>
          <div class="show-form">
            <%= f.label :title %><br>
            <%= f.text_field :title, autofocus: true, id:"inputTitle", class: "form-control book_title" %>
          </div>
          <div class="show-form">
            <%= f.label :opinion %><br>
            <%= f.text_area :body, autofocus: true, id:"inputBody", class: "form-control book_body" %>
          </div>
          <div class="show-form">
            <%= f.submit "Update Book",class: "btn btn-success" %>
          </div>
        <% end %>
        <%= link_to "Show", book_path(params[:id]), class: "edit_btn" %> | <%= link_to "Back", books_path, class: "edit_btn" %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div id="error_explanation" class="alert alert-danger">
        <h3 class="alert_message">
         <%= @book.errors.count %> error prohibited this obj from being saved:
        </h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
  <!--ここから左側-->
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= render 'users/list', book: @book %>
      </div>
  <!--ここまで左側-->
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
              <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                 <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                <% if book.favorited_by?(current_user) %>
                  <p id ="unlike-button">
                    <%= render "books/unlike", book: book %>
                  </p>
                  <% else %>
                  <p id ="like-button">
                    <%= render "books/like", book: book %>
                  </p>
                <% end %>
              </td>
              <td>
                コメント数：<%= book.book_comments.count %>
              </td>
            </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
  <!--ここから左側-->
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @book_user.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @book_user.user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @book_user.user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
        <%= link_to "", edit_user_path(@book_user.user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= render 'users/list', book: @book %>
      </div>

  <!--ここまで左側-->
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book_user.user.id) do %>
                 <%= attachment_image_tag @book_user.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %><br>
                 <%= @book_user.user.name %>
                <% end %>
              </td>
              <td><%= link_to @book_user.title, book_path(params[:id]) %></td>
              <td><%= @book_user.body %></td>
                            <td>
                <% if @book_user.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(@book_user), method: :delete do %>
                      <i class="fas fa-heart" style="color:red;"><%= @book_user.favorites.count %></i>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(@book_user), method: :post do %>
                      <i class="fas fa-heart"><%= @book_user.favorites.count %></i>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>
                コメント数：<%= @book_user.book_comments.count %>
              </td>
              <% if current_user.id==@book_user.user.id %>
              <td><%= link_to "Edit", edit_book_path(@book_user.id), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", "/books/#{@book_user.id}", class: "btn btn-sm btn-danger", method: :delete, data: {confirm: "本当に削除しますか？"}  %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
        <div class="comments">
          <%= render "books/show", book_user: @book_user %>
        </div>
        <div class="new-comment">
          <%= form_with(model:[@book_user, @book_comment], remote: true) do |f| %>
            <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" , class: "new-comment" %>
            <%= f.submit "送信" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/create.js.erb
$("#unlike-button").html("<%= j(render "books/unlike , book: book") %>")
$("#like-button").html("<%= j(render "books/like , book: book") %>")
$(".comments").html("<%= j(render "books/show, book_user.book_comments: @book_user.book_comments") %> ")

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<main>
    <div class="container">
      <div class="row">
        <div class="mx-auto" style="width: 540px;">
          <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
          <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>
          <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
            </div>
            <div class="row">
              <%= link_to "Sign Up", new_user_registration_path,class:"btn btn-success btn-sm btn-block sign_up" %>
            </div>
          </div>
        </div>
      </div>
    </div>
</main>

app/views/searches/_book.html.erb
 <table class="table">
   <thead>
     <tr>
       <th></th>
       <th>title</th>
       <th>opinion</th>
     </tr>
   </thead>
  <% books.each do |book| %>
   <tbody>
     <tr>
       <td>
        <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg' %>
       </td>
       <td><%= book.title %></td>
       <td><%= book.body %></td>
     </tr>
   </tbody>
  <% end %>
 </table>

app/views/searches/_user.html.erb
<table class="table">
   <thead>
     <tr>
       <th></th>
       <th>name</th>
       <th>introduction</th>
     </tr>
   </thead>
  <% users.each do |user| %>
   <tbody>
     <tr>
       <td>
        <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg' %>
       </td>
       <td><%= user.name %></td>
       <td><%= user.introduction %></td>
     </tr>
   </tbody>
  <% end %>
 </table>

app/views/searches/search.html.erb
<% if @model == 'user' %>
  <h3>Users search for"<%= @content %>"</h3>
  <%= render 'searches/user', users: @records %>
<% elsif @model == 'book' %>
  <h3>Books search for"<%= @content %>"</h3>
  <%= render 'searches/book', books: @records %>

<% else %>
none
<% end %>

app/views/users/_list.html.erb
        <%= form_with model:book, local:true do |f| %>
          <div class="show-form">
            <%= f.label :title %><br>
            <%= f.text_field :title, autofocus: true, id:"inputTitle", class: "form-control book_title" %>
          </div>
          <div class="show-form">
            <%= f.label :opinion %><br>
            <%= f.text_area :body, autofocus: true, id:"inputBody", class: "form-control book_body" %>
          </div>
          <div class="show-form">
            <%= f.submit "Create Book",class: "btn btn-success" %>
          </div>
        <% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<% if @user.errors.any? %>
<div class="container px-5 px-sm-0">
 <div class="row">
   <div id="error_explanation" class="alert alert-danger">
     <h3 class="alert_message">
      <%= @user.errors.count %> error prohibited this obj from being saved:
     </h3>
     <ul>
       <% @user.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
     </ul>
   </div>
 </div>
</div>
<% end %>
<%= form_with model:@user, url:"/users/#{@user.id}", local:true do |f| %>
 <div class="show-form">
  <%= f.label :name %><br>
  <%= f.text_field :name, autofocus: true, id:"inputName", class: "form-control book_name" %>
 </div>
 <div class="show-form">
  <%= f.label :image %><br>
  <%= f.attachment_field :profile_image %>
 </div>
 <div class="show-form">
  <%= f.label :introduction %><br>
  <%= f.text_area :introduction, autofocus: true, id:"inputIntrpduction", class: "form-control book_introduction" %>
 </div>
 <%= f.submit "Update User",class: "btn btn-secondary" %>
<% end %>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<h1>Follow Users</h1>
<% if @user.followings.count >=  1 %>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
        </tr>
      </thead>
    <% @users.each do |user| %>
      <tbody>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %></td>
          <td><%= user.name %></td>
          <td>フォロー数:<%= user.followings.count %></td>
          <td>フォロワー数<%= user.followers.count %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      </tbody>
    <% end %>
    </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
  <!--ここから左側-->
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= render 'users/list', book: @book %>
      </div>
  <!--ここまで左側-->
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
              <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
              </td>
              <td><%= user.name %></td>
              <td>フォロー数:<%= user.followings.count %></td>
              <td>フォロワー数<%= user.followers.count %></td>
              <td>
                <% if current_user != user %>
                  <% if user.is_followed_by?(current_user) %>
                    <%= link_to "フォロー外す", user_relationships_path(user), method: :delete %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(user), method: :post %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
  <!--ここから左側-->
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size:'100x100' %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
            <tr>
              <th>follows</th>
              <th>
                <%= link_to @user.followings.count, followings_user_path(@user) %>
              </th>
            </tr>
            <tr>
              <th>followers</th>
              <th>
                <%= link_to @user.followers.count, followers_user_path(@user) %>
              </th>
            </tr>
          </tbody>
        </table>
        <% if current_user != @user %>
          <% if @user.is_followed_by?(current_user) %>
            <%= link_to "フォロー外す", user_relationships_path(@user), class: "btn btn btn-danger mb-3", method: :delete %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(@user), class: "btn btn btn-primary mb-3", method: :post %>
           <% end %>
        <% end %>
        <div class="row">
          <%= link_to "", edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= render 'users/list', book: @book %>
      </div>
  <!--ここまで左側-->
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
              <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>
                コメント数：<%= book.book_comments.count %>
              </td>
            </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>