config/routes.rb
Rails.application.routes.draw do
  get 'search' => "searches#search"
  get 'favorites/create'
  get 'favorites/destroy'
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about"
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
  resources :books, only: [:index,:show,:create,:destroy,:edit,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: {minimum: 2,maximum: 20},uniqueness: true
  validates :introduction, length: {maximum: 50}

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # フォロー機能
  has_many :relationships, foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :following

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end
  # /フォロー機能
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def ensure_current_user
    if current_user.id != params[:id].to_i
     redirect_to user_path(current_user.id)
    end
  end

  def require_login
    unless current_user
        redirect_to new_user_session_path, notice: 'Please sign in to get started!'
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :require_login
  before_action :ensure_current_user_book, {only: [:edit]}

  def index
    @book=Book.new
    @user=current_user
    @books=Book.all
  end

  def show
    @book_user=Book.find(params[:id])
    @book=Book.new
    @book_comment=BookComment.new
  end

  def create
    @book=Book.new(book_params)
    @book.user_id= current_user.id
    if @book.save
      flash[:success]="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user=current_user
      @books=Book.all
      render "books/index"
    end
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:success]="You have updated book successfully."
    else
      render "books/edit"
    end
  end

    private

  def book_params
    params.require(:book).permit(:title,:body,:user_id)
  end
end

  def ensure_current_user_book
    book = Book.find(params[:id])
    if current_user.id != book.user.id
     redirect_to books_path
    end
  end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      elsif method == 'forward'
        User.where('name LIKE ?', "#{content}%")
      elsif method == 'rear'
        User.where('name LIKE ?', "%#{content}")
      elsif method == 'partial'
        User.where('name LIKE ?', "%#{content}%")
      end
    elsif model == 'book'
      if method == 'perfect'
        Book.where(body: content)
      elsif method == 'forward'
        Book.where('body LIKE ?', "#{content}%")
      elsif method == 'rear'
        Book.where('body LIKE ?', "%#{content}")
      elsif method == 'partial'
        Book.where('body LIKE ?', "%#{content}%")
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  before_action :ensure_current_user, {only: [:edit]}

  def index
    @user=current_user
    @book=Book.new
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
    @books=Book.where(user_id: @user.id)
    @book=Book.new
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=current_user
    if @user.update(user_params)
     redirect_to user_path(current_user.id)
     flash[:success]="You have updated user successfully."
    else
      render "users/edit"
    end
  end

  def followings
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

    private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Ver2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navber navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to " Home", user_path(current_user.id), class:"fas fa-home nav-link text-light" %>
                </li>
                <li>
                  <%= link_to " Users", users_path, class:"fas fa-users nav-link text-light" %>
                </li>
                <li>
                  <%= link_to " Books", books_path, class:"fas fa-book-open nav-link text-light" %>
                </li>
                <li>
                  <%= link_to " logout", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %>
                </li>
              <% else %>
                <li>
                  <%= link_to " Home","/", class:"fas fa-home nav-link text-light" %>
                </li>
                <li>
                  <%= link_to " About","/home/about", class:"fas fa-link nav-link text-light" %>
                </li>
                <li>
                  <%= link_to " sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light" %>
                </li>
                <li>
                  <%= link_to " login", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if user_signed_in? %>
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%= f.text_field :content %>
      <%= f.select :model, ({"User" => "user","Book" =>"book"}) %>
      <%= f.select :method, ({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "rear", "部分一致" => "partial" }) %>
      <%= f.submit '検索' %>
    <% end %>
    <% end %>
    <%= yield %>
    <footer>
      <div class='container mt-5'>
    	    <div class='mx-auto'>
    		    <p>CopyRight Infratop.inc</p>
        	</div>
      </div>
    </footer>
  </body>
</html>